### ISSUE TITLE
Dark mode not working on the new song page

### ISSUE THREAD

**Issue by Uri6** [Uri6/Genius-Enhancer#39]
**Username on Genius**
Lyulf

**Browser**
Chrome

**GE version**

**Bug description**
Dark mode only works when I switch to the old song page, or enable it to force it to go there: the new song page never shows dark mode, not even after ctrl+f5-ing.

**Steps to Reproduce**

**Screenshot**
![]()

**Comment by Nowaha** [comment]
Couldn't put in 1.0.1 as a version for some reason, but it's 1.0.1

**Comment by Uri6** [comment]
Duplicate of #23
