### ISSUE TITLE
The metadata adder fails on long albums

### ISSUE THREAD

**Issue by Uri6** [Uri6/Genius-Enhancer#9]
**Username on Genius**
Vlad2D

**Browser**
Chrome

**GE version**
0.9.3

**Bug description**
On the really long albums Genius Enchancer just breaks. After track 13 it will stop showing if the bio, release date, etc. is in the song. ANTIHYPETRAIN is perfect to test this kind of stuff I swear :)

![chrome_DL3LgAGsax](https://github.com/Uri6/Genius-Enhancer-Beta/assets/93275900/34fa6087-0d05-4cd9-b258-41b2dac2a23e)

**Comment by StenIsMe** [comment]
This is not an issue anymore as far as I can tell, it loaded perfectly on 229 tracks album just fine. Can be closed.
